# Generated by Django 4.1.2 on 2024-05-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starsBlog', '0002_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('AR', 'Arabic'), ('EN', 'English')], default='EN', max_length=2),
        ),
    ]
