# Generated by Django 4.1.2 on 2024-05-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starsBlog', '0003_post_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
    ]
